#!/bin/sh
#/ Usage: curl -L https://github.com/spraints/homenetwork/raw/master/run | bash

set -e

sudodoas() {
  echo Running "$@"
  doas "$@"
}

if which sudo >/dev/null 2>/dev/null; then
  sudo -p "We need sudo privileges to run puppet. Please type your password: " true
  sudo=sudo
else
  if which doas >/dev/null 2>/dev/null; then
    if doas -n true; then
      sudo=doas
    else
      if ! sudodoas true; then
        echo You gotta enable doas first.
        exit 1
      fi
      sudo=sudodoas
    fi
  fi
fi

step() {
  echo '====>' "$@"
}

banner() {
  echo "========================================================================"
  echo "= $*"
  echo "========================================================================"
}

# Ensure that puppet (e.g. 3.7.3), curl, git, bundler, and sudo are installed.
case `uname -s` in
  Linux)
    if ! dpkg -s puppet-common >/dev/null 2>/dev/null; then
      step Install puppet per https://docs.puppetlabs.com/guides/install_puppet/install_debian_ubuntu.html
      (
        set -e
        cd /tmp
        deb=puppetlabs-release-trusty.deb
        curl -O https://apt.puppetlabs.com/${deb}
        sudo dpkg -i ${deb}
        rm ${deb}
      )
      packages_to_install="${packages_to_install} puppet"
    fi

    if ! dpkg -s git >/dev/null 2>/dev/null; then
      step Install git
      packages_to_install="${packages_to_install} git"
    fi

    if ! dpkg -s bundler >/dev/null 2>/dev/null; then
      step Install bundler
      packages_to_install="${packages_to_install} bundler"
    fi

    if [ -n "${packages_to_install}" ]; then
      sudo apt-get update
      sudo apt-get install -y ${packages_to_install}
    fi

    ;;

  OpenBSD)
    pkg_info -q -e 'git->=0.0'            || packages="$packages git"
    pkg_info -q -e 'curl->=0.0'           || packages="$packages curl"
    pkg_info -q -e 'ruby22-bundler->=0.0' || packages="$packages ruby22-bundler"
    pkg_info -q -e 'puppet->=0.0'         || packages="$packages puppet"

    case `uname -r` in
      5.8)
        pkg_info -q -e facter-2.4.4p2 || packages="$packages facter-2.4.4p2"
        ;;

      *)
        pkg_info -q -e 'facter->0.0'  || packages="$packages facter"
        ;;
    esac

    test -n "$packages" && $sudo pkg_add $packages

    for exe in bundle erb gem hiera irb rake rdoc ri ruby; do
      if [ ! -f /usr/local/bin/$exe ]; then
        $sudo ln -s "$exe"22 /usr/local/bin/$exe
      fi
    done
    ;;

  *)
    echo `uname -s` is not supported.
    exit 1
    ;;
esac

repo_path=/var/local/homenetwork-puppet
if ! test -d ${repo_path}; then
  step Initialize repository
  $sudo mkdir -p ${repo_path}
  $sudo chown `id -u` ${repo_path}
  git init ${repo_path}
fi

cd ${repo_path}

old_branch=master
new_branch=master
if [ -f .branch ]; then
  old_branch="$(cat .branch)"
  new_branch="${old_branch}"
fi
if [ -n "${PUPPET_BRANCH}" ]; then
  new_branch="${PUPPET_BRANCH}"
  echo "${new_branch}" > .branch
fi
if [ "${old_branch}" != "${new_branch}" ]; then
  banner Switching from ${old_branch} to ${new_branch}
fi

step Get latest version
if ! git remote set-url origin https://github.com/spraints/homenetwork; then
  git remote add origin https://github.com/spraints/homenetwork
fi
git fetch --prune origin

ref="origin/${new_branch}"
if ! git rev-parse "${ref}" >/dev/null 2>/dev/null; then
  banner "${new_branch} has been deleted. Reverting to master."
  rm .branch
  ref="origin/master"
fi
git reset --hard "${ref}"
git clean -d -n
git --no-pager show -q HEAD

script/bootstrap

step hieradata
hiera_config=${repo_path}/hiera.yaml
if [ -f "${hiera_config}" ]; then
  script/update-hieradata
  hiera_opts="--hiera_config ${repo_path}/hiera.yaml"
else
  echo Set HIERA_GIST_ID and run script/update-hieradata to create hiera.yaml
fi

config_version_cmd="git --git-dir '${repo_path}' rev-parse HEAD"

step Apply
set -x
$sudo puppet apply --show_diff --verbose "$@" --config_version "${config_version_cmd}" --modulepath ${repo_path}/modules ${hiera_opts} ${repo_path}/manifests/
