#!/bin/bash
#/ Usage: curl -L https://github.com/spraints/homenetwork/raw/master/run | bash

set -e

sudo -p "We need sudo privileges to run puppet. Please type your password: " /bin/true

step() {
  echo '====>' "$@"
}

banner() {
  echo ========================================================================
  echo = "$@"
  echo ========================================================================
}

if ! dpkg -s puppet-common >/dev/null 2>/dev/null; then
  step Install puppet per https://docs.puppetlabs.com/guides/install_puppet/install_debian_ubuntu.html
  (
    set -e
    cd /tmp
    deb=puppetlabs-release-trusty.deb
    curl -O https://apt.puppetlabs.com/${deb}
    sudo dpkg -i ${deb}
    rm ${deb}
  )
  packages_to_install="${packages_to_install} puppet"
fi

if ! dpkg -s git >/dev/null 2>/dev/null; then
  step Install git
  packages_to_install="${packages_to_install} git"
fi

if ! dpkg -s bundler >/dev/null 2>/dev/null; then
  step Install bundler
  packages_to_install="${packages_to_install} bundler"
fi

if [ -n "${packages_to_install}" ]; then
  sudo apt-get update
  sudo apt-get install -y ${packages_to_install}
fi

repo_path=/var/local/homenetwork-puppet
if ! test -d ${repo_path}; then
  step Initialize repository
  sudo mkdir -p ${repo_path}
  sudo chown `id -u` ${repo_path}
  git init ${repo_path}
fi

cd ${repo_path}

old_branch=master
new_branch=master
if [ -f .branch ]; then
  old_branch="$(cat .branch)"
  new_branch="${old_branch}"
fi
if [ -n "${PUPPET_BRANCH}" ]; then
  new_branch="${PUPPET_BRANCH}"
  echo "${new_branch}" > .branch
fi
if [ "${old_branch}" != "${new_branch}" ]; then
  banner Switching from ${old_branch} to ${new_branch}
fi

step Get latest version
if ! git remote set-url origin https://github.com/spraints/homenetwork; then
  git remote add origin https://github.com/spraints/homenetwork
fi
git fetch --prune origin

ref="origin/${new_branch}"
if ! git rev-parse "${ref}" >/dev/null 2>/dev/null; then
  banner "${new_branch} has been deleted. Reverting to master."
  rm .branch
  ref="origin/master"
fi
git reset --hard "${ref}"
git clean -d -n

script/bootstrap

step Apply
sudo puppet apply "$@" --modulepath ${repo_path}/modules ${repo_path}/manifests/
