#!/usr/bin/env ruby

require "net/http"
require "json"

def main(gist_id)
  write_hiera_config
  fetch_hiera_data(gist_id)
end

def write_hiera_config
  File.write File.join(root, "hiera.yaml"), <<HIERA
---
:hierarchy:
  - common

:backends:
  - yaml

:yaml:
  :datadir: "#{root}/hieradata
HIERA
end

def fetch_hiera_data(gist_id)
  run "mkdir", "-p", hiera_dir
  gist_info = JSON.load(Net::HTTP.get(URI("https://api.github.com/gists/#{gist_id}")))
  gist_info["files"].each do |name, file_info|
    run "curl", "-Lf", "-o", File.join(hiera_dir, name), file_info["raw_url"]
  end
end

def run(*command)
  puts "$ #{command.join(" ")}"
  system(*command) or raise $!.inspect
end

def root
  File.dirname(File.dirname(__FILE__))
end

def hiera_dir
  File.join(root, "hieradata")
end

main(*ARGV)
