#!/usr/bin/env ruby

require "net/https"
require "json"

def main
  write_hiera_config
  fetch_hiera_data
end

def write_hiera_config
  File.write File.join(root, "hiera.yaml"), <<HIERA
---
:hierarchy:
  - common

:backends:
  - yaml

:yaml:
  :datadir: "#{hiera_dir}"
HIERA
end

def fetch_hiera_data
  run "mkdir", "-p", hiera_dir
  gist_info["files"].each do |name, file_info|
    run "curl", "-Lf", "-o", File.join(hiera_dir, name), file_info["raw_url"]
  end
end

def gist_info
  http = Net::HTTP.new("api.github.com", 443)
  http.use_ssl = true
  http.start do |http|
    res = http.request_get("/gists/#{gist_id}")
    res.value # raises, if error
    return JSON.load(res.body)
  end
end

def run(*command)
  puts "$ #{command.join(" ")}"
  system(*command) or raise $!.inspect
end

def gist_id
  ENV["HIERA_GIST_ID"] or raise "HIERA_GIST_ID was not defined!"
end

def root
  File.dirname(File.dirname(__FILE__))
end

def hiera_dir
  File.join(root, "hieradata")
end

def hiera_config_path
  File.join(root, ".hiera_config")
end

def load_config
  File.read(hiera_config_path).lines.each do |line|
    name, value = line.chomp.split("=", 2)
    ENV[name] ||= value
  end
end

load_config
main
