exttraffic:
  :metrics:
    - snmp/if_octets-mgi1
  :url: exttraffic
  :profile_name: exttraffic
  :hosts:
    - airport

extpackets:
  :metrics:
    - snmp/if_packets-mgi1
    - snmp/if_errors-mgi1
  :url: extpackets
  :profile_name: extpackets
  :hosts:
    - airport

ping:
  :metrics:
    - ping/ping-10.5.49.1
    - ping/ping-192.168.3.1
    - ping/ping-github.com
    - ping/ping-8.8.8.8
  :hosts:
    - minibuntu
  :url: ping
  :profile_name: ping
