exttraffic:
  :metrics:
    - snmp/if_octets-mgi1
  :url: exttraffic
  :profile_name: exttraffic
  :hosts:
    - airport

extpackets:
  :metrics:
    - snmp/if_packets-mgi1
    - snmp/if_errors-mgi1
  :url: extpackets
  :profile_name: extpackets
  :hosts:
    - airport

ping:
  :metrics:
    - ping/ping-10.5.49.1
    - ping/ping-192.168.3.1
    - ping/ping-github.com
    - ping/ping-8.8.8.8
  :hosts:
    - minibuntu
  :url: ping
  :profile_name: ping

pingdrop:
  :metrics:
    - ping/ping_droprate-10.5.49.1
    - ping/ping_droprate-192.168.3.1
    - ping/ping_droprate-github.com
    - ping/ping_droprate-8.8.8.8
  :hosts:
    - minibuntu
  :url: pingdrop
  :profile_name: pingdrop

weatherpressure:
  :metrics:
    - weather-kinpicka2/gauge-pressure_inhg
  :hosts:
    - minibuntu
  :url: weatherpressure
  :profile_name: weatherpressure

weatheroutdoortemp:
  :metrics:
    - weather-kinpicka2/temperature-outdoor_f
  :hosts:
    - minibuntu
  :url: weatheroutdoortemp
  :profile_name: weatheroutdoortemp

weatherindoortemp:
  :metrics:
    - weather-kinpicka2/temperature-indoor_f
  :hosts:
    - minibuntu
  :url: weatherindoortemp
  :profile_name: weatherindoortemp
